default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: snow_maps_development


test:
  <<: *default
  database: snow_maps_test


production:
  <<: *default
  host: localhost
  database: snow_maps_production
  username: snow_maps
  password: <%= ENV['SNOW_MAPS_DATABASE_PASSWORD'] %>